/* eslint-disable */
// Generated by Wrangler by running `wrangler types --config=workers/redirect/wrangler.jsonc --include-runtime=false workers/redirect/src/worker-configuration.d.ts` (hash: 6430809d96b38cf0b0e3b01b4a508947)
interface __BaseEnv_Env {
	REDIRECTS: KVNamespace;
	SCANS: AnalyticsEngineDataset;
	HMAC_SECRET: string;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./index");
	}
	interface PreviewEnv {
		REDIRECTS: KVNamespace;
		SCANS: AnalyticsEngineDataset;
		HMAC_SECRET: string;
	}
	interface ProductionEnv {
		REDIRECTS: KVNamespace;
		SCANS: AnalyticsEngineDataset;
		HMAC_SECRET: string;
	}
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "HMAC_SECRET">> {}
}
