/* eslint-disable */
// Generated by Wrangler by running `wrangler types --config=workers/cache-sync/wrangler.jsonc --include-runtime=false workers/cache-sync/src/worker-configuration.d.ts` (hash: 468419b7870ecc3dbf7a717c17e2422c)
interface __BaseEnv_Env {
	REDIRECTS: KVNamespace;
	SUPABASE_URL: "https://yeohcglutyegbvafxisl.supabase.co" | "https://adrcdewvydtslqkokohy.supabase.co" | "http://127.0.0.1:54321";
	SUPABASE_SECRET_KEY: string;
	SYNC_WEBHOOK_SECRET: string;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./index");
	}
	interface PreviewEnv {
		REDIRECTS: KVNamespace;
		SUPABASE_URL: "https://yeohcglutyegbvafxisl.supabase.co";
		SUPABASE_SECRET_KEY: string;
		SYNC_WEBHOOK_SECRET: string;
	}
	interface ProductionEnv {
		REDIRECTS: KVNamespace;
		SUPABASE_URL: "https://adrcdewvydtslqkokohy.supabase.co";
		SUPABASE_SECRET_KEY: string;
		SYNC_WEBHOOK_SECRET: string;
	}
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "SUPABASE_URL" | "SUPABASE_SECRET_KEY" | "SYNC_WEBHOOK_SECRET">> {}
}
