import { useEffect, useMemo, useState } from "react";
import type { AnalyticsSummary, Campaign, Location } from "../../domain/models";
import { ErrorBanner, LoadingState, PageHeader } from "../components/Page";
import { LocationMap } from "../components/LocationMap";
import { errorMessage, qrRepository } from "../services";

export function AnalyticsPage({ workspaceId }: { workspaceId: string }) {
  const [days, setDays] = useState(30); const [summary, setSummary] = useState<AnalyticsSummary>(); const [campaigns, setCampaigns] = useState<Campaign[]>([]); const [locations, setLocations] = useState<Location[]>([]); const [error, setError] = useState("");
  useEffect(() => { const to = new Date(); const from = new Date(Date.UTC(to.getUTCFullYear(), to.getUTCMonth(), to.getUTCDate() - days + 1)); setSummary(undefined); setError(""); void Promise.all([qrRepository.getAnalytics(workspaceId, from.toISOString(), to.toISOString()), qrRepository.listCampaigns(workspaceId), qrRepository.listLocations(workspaceId)]).then(([analytics, campaignValues, locationValues]) => { setSummary(analytics); setCampaigns(campaignValues); setLocations(locationValues); }).catch((cause) => setError(errorMessage(cause))); }, [days, workspaceId]);
  const campaignNames = useMemo(() => new Map(campaigns.map((campaign) => [campaign.id, campaign.name])), [campaigns]); const locationNames = useMemo(() => new Map(locations.map((location) => [location.id, location.name])), [locations]); const scansByLocation = useMemo(() => new Map((summary?.locations ?? []).filter((item) => item.locationId).map((item) => [item.locationId!, item.scans])), [summary]);
  return <><PageHeader eyebrow="Performance" title="Analytics" description="Die letzten zwei UTC-Tage aus Analytics Engine, ältere Tage aus langfristigen PostgreSQL-Rollups." actions={<label className="range-select">Zeitraum<select value={days} onChange={(event) => setDays(Number(event.target.value))}><option value={7}>7 Tage</option><option value={30}>30 Tage</option><option value={90}>90 Tage</option><option value={365}>1 Jahr</option><option value={730}>2 Jahre</option></select></label>} />{error && <ErrorBanner message={error} />}{!summary && !error ? <LoadingState label="Analytics werden abgefragt…" /> : summary && <><section className="metric-grid"><article className="metric-card"><span>Scans</span><strong>{formatNumber(summary.totalScans)}</strong><small>Sampling-korrigiert</small></article><article className="metric-card"><span>Unique-IP-Tage</span><strong>{formatNumber(summary.uniqueIpDays)}</strong><small>Täglich rotierender Fingerprint</small></article><article className="metric-card"><span>Aktive Standorte</span><strong>{summary.locations.filter((item) => item.locationId && item.scans > 0).length}</strong><small>Im gewählten Zeitraum</small></article></section><section className="panel section-block"><h2>Scans im Zeitverlauf</h2><SeriesChart values={summary.series} /></section><div className="two-column section-block"><section className="panel"><h2>Kampagnen</h2><Ranking rows={summary.campaigns.map((item) => ({ id: item.campaignId, name: campaignNames.get(item.campaignId) ?? item.campaignId, value: item.scans }))} /></section><section className="panel"><h2>Standorte</h2><Ranking rows={summary.locations.map((item) => ({ id: item.locationId ?? "none", name: item.locationId ? locationNames.get(item.locationId) ?? item.locationId : "Ohne Standort", value: item.scans }))} /></section></div><section className="panel section-block"><h2>Scan-Karte</h2><LocationMap locations={locations} scansByLocation={scansByLocation} /></section></>}</>;
}

function SeriesChart({ values }: { values: AnalyticsSummary["series"] }) {
  if (values.length === 0) return <div className="chart-empty">Im Zeitraum wurden keine Scans erfasst.</div>;
  const max = Math.max(...values.map((item) => item.scans), 1); const width = 900; const height = 260; const padding = 28; const points = values.map((item, index) => `${padding + index / Math.max(values.length - 1, 1) * (width - padding * 2)},${height - padding - item.scans / max * (height - padding * 2)}`).join(" ");
  return <div className="chart"><svg viewBox={`0 0 ${width} ${height}`} role="img" aria-label="Scans im Zeitverlauf"><line x1={padding} y1={height - padding} x2={width - padding} y2={height - padding} /><polyline points={points} /><g>{values.map((item, index) => <circle key={item.date} cx={padding + index / Math.max(values.length - 1, 1) * (width - padding * 2)} cy={height - padding - item.scans / max * (height - padding * 2)} r="4"><title>{new Date(item.date).toLocaleDateString("de-DE")}: {formatNumber(item.scans)} Scans</title></circle>)}</g></svg><div className="chart-labels"><span>{new Date(values[0].date).toLocaleDateString("de-DE")}</span><span>Maximum {formatNumber(max)}</span><span>{new Date(values[values.length - 1].date).toLocaleDateString("de-DE")}</span></div></div>;
}

function Ranking({ rows }: { rows: Array<{ id: string; name: string; value: number }> }) { const max = Math.max(...rows.map((row) => row.value), 1); return rows.length === 0 ? <p>Keine Daten vorhanden.</p> : <ol className="ranking">{rows.map((row) => <li key={row.id}><div><strong>{row.name}</strong><span>{formatNumber(row.value)}</span></div><span className="ranking-bar"><i style={{ width: `${row.value / max * 100}%` }} /></span></li>)}</ol>; }
function formatNumber(value: number) { return new Intl.NumberFormat("de-DE", { maximumFractionDigits: 0 }).format(value); }
