import { useCallback, useEffect, useState, type FormEvent } from "react";
import { Link } from "react-router-dom";
import type { Campaign } from "../../domain/models";
import { ConfirmButton, EmptyState, ErrorBanner, LoadingState, Notice, PageHeader } from "../components/Page";
import { errorMessage, qrRepository } from "../services";

export function CampaignsPage({ workspaceId }: { workspaceId: string }) {
  const [campaigns, setCampaigns] = useState<Campaign[]>([]); const [loading, setLoading] = useState(true); const [error, setError] = useState(""); const [notice, setNotice] = useState("");
  const [name, setName] = useState(""); const [description, setDescription] = useState(""); const [destinationUrl, setDestinationUrl] = useState(""); const [busy, setBusy] = useState(false);
  const load = useCallback(async () => { setLoading(true); setError(""); try { setCampaigns(await qrRepository.listCampaigns(workspaceId)); } catch (cause) { setError(errorMessage(cause)); } finally { setLoading(false); } }, [workspaceId]);
  useEffect(() => { void load(); }, [load]);
  async function create(event: FormEvent) { event.preventDefault(); setBusy(true); setError(""); try { await qrRepository.updateCampaign({ workspaceId, name, description, destinationUrl }); setName(""); setDescription(""); setDestinationUrl(""); setNotice("Kampagne wurde angelegt."); await load(); } catch (cause) { setError(errorMessage(cause)); } finally { setBusy(false); } }
  async function archive(campaign: Campaign) { try { await qrRepository.archiveCampaign(workspaceId, campaign.id); setNotice(`„${campaign.name}“ wurde archiviert. Bestehende QR-Routen werden deaktiviert.`); await load(); } catch (cause) { setError(errorMessage(cause)); } }
  async function remove(campaign: Campaign) { try { await qrRepository.deleteCampaign(workspaceId, campaign.id); setNotice(`„${campaign.name}“ wurde gelöscht.`); await load(); } catch (cause) { setError(errorMessage(cause)); } }
  return <><PageHeader eyebrow="Campaign Management" title="Kampagnen" description="Ziele, Status und Druckmaterial eines Workspaces verwalten." />{error && <ErrorBanner message={error} onRetry={() => void load()} />}{notice && <Notice>{notice}</Notice>}<div className="two-column"><section className="panel"><h2>Neue Kampagne</h2><form onSubmit={create}><label>Name<input required maxLength={120} value={name} onChange={(event) => setName(event.target.value)} /></label><label>Beschreibung<textarea rows={4} value={description} onChange={(event) => setDescription(event.target.value)} /></label><label>Ziel-URL<input required type="url" value={destinationUrl} onChange={(event) => setDestinationUrl(event.target.value)} placeholder="https://example.com/landingpage" /></label><button className="button" disabled={busy}>{busy ? "Wird angelegt…" : "Kampagne anlegen"}</button></form></section><section className="panel"><div className="section-header"><div><h2>Workspace-Kampagnen</h2><p>{campaigns.length} Kampagnen</p></div></div>{loading ? <LoadingState /> : campaigns.length === 0 ? <EmptyState title="Noch keine Kampagnen">Lege links die erste Kampagne an.</EmptyState> : <div className="card-list">{campaigns.map((campaign) => <article className="item-card" key={campaign.id}><div className="card-topline"><span className={`status ${campaign.status.toLowerCase()}`}>{campaign.status}</span><time dateTime={campaign.updatedAt}>{new Date(campaign.updatedAt).toLocaleDateString("de-DE")}</time></div><h3>{campaign.name}</h3>{campaign.description && <p>{campaign.description}</p>}<a href={campaign.destinationUrl} target="_blank" rel="noreferrer">{campaign.destinationUrl}</a><div className="card-actions"><Link className="text-link" to={`/campaigns/${campaign.id}`}>Details öffnen</Link>{campaign.status !== "ARCHIVED" && <ConfirmButton label="Archivieren" confirmText={`Kampagne „${campaign.name}“ archivieren? Alle zugehörigen QR-Routen werden deaktiviert.`} onConfirm={() => archive(campaign)} />}{campaign.status === "ARCHIVED" && <ConfirmButton label="Löschen" confirmText={`Archivierte Kampagne „${campaign.name}“ endgültig löschen? Das funktioniert nur ohne Druckmaterial.`} onConfirm={() => remove(campaign)} />}</div></article>)}</div>}</section></div></>;
}
